# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f012e20c6773636069b358eaf31e8b182cf8218a48e15e7c9e2d16834079e607c3644d7094e0de9badc3f0614ee832f4bce3f36257f2ef698eddcda96e7fa5

test:
  secret_key_base: 768ff5b4a4cf59cdf8024d84dbe28b793e3abe711d87fa8de113cfe7ec27bd77e2115385e1380162c8dcaea2764dd52179284c2661b4565cd404b7e31bbab430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
